MPESA_CONSUMER_KEY: 'DJRENx2wMGKTmCVMcJowAgqmaUqMLHzo'
MPESA_CONSUMER_SECRET: 'sAo53qTzyYV4ApbD'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://2744-154-122-78-150.eu.ngrok.io/'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"